name: ci

on:
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          ./bin/youtube-dl --config-location config.txt
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
