name: ci

on:
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: download
        run: |
          git config --local user.email "justjavac@gmail.com"
          git config --local user.name "迷渡"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          ./bin/youtube-dl --config-location config.txt
      - name: Upload firmware to cowtransfer
        id: cowtransfer
        if: always()
        run: |
          curl -sL https://git.io/cowtransfer | sh
          ./cowtransfer-uploader -s -p 16 --hash /opt/downloads/*.trx 2>&1 | tee cowtransfer.log
          echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
          echo "DOWNLOADURL=$(cat cowtransfer.log | grep -o -E "https?://[a-zA-Z0-9\.\/_&=@$%?~#-]*")" >> $GITHUB_ENV
